#!/bin/bash

1. start MySQL
systemctl start mariadb

2. create database
CREATE DATABASE httptables CHARACTER SET utf8;

3. init db
python3 manage.py migrate

3. set admin password
python3 manage.py createsuperuser
default user:admin
default password: 123456@admin
