#!/bin/bash

1. install base package
run depends.sh

2. start MySQL
systemctl start mariadb

3. create database
CREATE DATABASE httptables CHARACTER SET utf8;

4. import SQL
login to MySQL
MariaDB [(none)]> use httptables
MariaDB [httptables]> source httptables.dump.sql

note:
default user:admin
default password: 123456@admin

5. start django
run manager/run.sh
